# Site settings
baseurl = "/"
languageCode = "en-us"
title = "IoTone, Inc. Home"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-70840299-1"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "IoTone, Inc."
    subtitle = "Unified Device Intelligence - IoTone is an Open Source focused software and hardware company"
    author = "IoTone, Inc."
    description = "IoTone, Inc., Home page"
    keywords = "IoT, Device, Embedded, Protocol, AI, MachineLearning, VR, AR, Augmented Reality, Virtual Reality, NFC, Android, iOS, Hyperlocal"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "GO"

    # Footer text
    footertext = "Copyright &copy; IoTone, Inc. 2014-2025. For Sponsorship of Open Source, <a href='mailto:info@iotone.io'>Contact Us</a>"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
